import Foundation

// GENERATED FILE — do not edit. Run `npm run db:types` (or `make codegen`)
// after schema changes. Generated by `scripts/gen-types.mjs`.
//
// Each table maps to an enum namespace containing a `Row: Codable` struct.
// Use these as DTOs at the service boundary; map to/from your domain types
// (e.g. Models/UserProfile.swift) inside the corresponding service.

// swiftlint:disable nesting

enum FollowsSchema {
    /// Row shape for the `public.follows` table.
    struct Row: Codable, Equatable {
        let followerId: UUID
        let followeeId: UUID
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case followerId = "follower_id"
            case followeeId = "followee_id"
            case createdAt = "created_at"
        }
    }
}

enum MediaSchema {
    /// Row shape for the `public.media` table.
    struct Row: Codable, Equatable {
        // metadata: jsonb (omitted — decode via a dedicated DTO when needed)
        let id: UUID
        let kind: String
        let title: String
        let year: Int?
        let primaryCreator: String?
        let coverUrl: String?
        let externalId: String?
        let externalSource: String?
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case kind
            case title
            case year
            case primaryCreator = "primary_creator"
            case coverUrl = "cover_url"
            case externalId = "external_id"
            case externalSource = "external_source"
            case createdAt = "created_at"
        }
    }
}

enum PostsSchema {
    /// Row shape for the `public.posts` table.
    struct Row: Codable, Equatable {
        let id: UUID
        let authorId: UUID
        let mediaId: UUID
        let action: String
        let rating: Double?
        let caption: String?
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case authorId = "author_id"
            case mediaId = "media_id"
            case action
            case rating
            case caption
            case createdAt = "created_at"
        }
    }
}

enum ProfilesSchema {
    /// Row shape for the `public.profiles` table.
    struct Row: Codable, Equatable {
        let id: UUID
        let username: String
        let displayName: String?
        let avatarUrl: String?
        let bio: String?
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case username
            case displayName = "display_name"
            case avatarUrl = "avatar_url"
            case bio
            case createdAt = "created_at"
        }
    }
}

// swiftlint:enable nesting
