import Foundation

// GENERATED FILE — do not edit. Run `npm run db:types` (or `make codegen`)
// after schema changes. Generated by `scripts/gen-types.mjs`.
//
// Each table maps to an enum namespace containing a `Row: Codable` struct.
// Use these as DTOs at the service boundary; map to/from your domain types
// (e.g. Models/UserProfile.swift) inside the corresponding service.

// swiftlint:disable nesting

enum PostsSchema {
    /// Row shape for the `public.posts` table.
    struct Row: Codable, Equatable {
        let id: UUID
        let authorId: UUID
        let caption: String
        let mediaUrl: String?
        let likeCount: Int
        let commentCount: Int
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case authorId = "author_id"
            case caption
            case mediaUrl = "media_url"
            case likeCount = "like_count"
            case commentCount = "comment_count"
            case createdAt = "created_at"
        }
    }
}

enum ProfilesSchema {
    /// Row shape for the `public.profiles` table.
    struct Row: Codable, Equatable {
        let id: UUID
        let username: String
        let displayName: String?
        let avatarUrl: String?
        let bio: String?
        let createdAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case username
            case displayName = "display_name"
            case avatarUrl = "avatar_url"
            case bio
            case createdAt = "created_at"
        }
    }
}

// swiftlint:enable nesting
