#!/usr/bin/env node
// =============================================================================
// gen-types.mjs — generate Swift Codable types from the Supabase schema.
// =============================================================================
// Connects to the linked Supabase Postgres (via SUPABASE_DB_URL in .env),
// reads information_schema for every table in `public`, and writes
// ios/Venn/Models/SupabaseSchema.swift.
//
// Run via `npm run db:types` (which loads .env automatically).
//
// Why custom: Supabase CLI's `gen types --lang=swift` requires Docker.
// We don't run Docker locally, so this script bypasses the CLI and
// queries Postgres directly. Single-file maintenance burden in
// exchange for zero-dep dev environments.
// =============================================================================

import pg from "pg";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const OUTPUT = "ios/Venn/Models/SupabaseSchema.swift";

const dbUrl = process.env.SUPABASE_DB_URL;
if (!dbUrl) {
  console.error(
    "error: SUPABASE_DB_URL is not set. Add it to .env (see .env.example) " +
      "and run `npm run db:types` again."
  );
  process.exit(1);
}

const client = new pg.Client({ connectionString: dbUrl });
await client.connect();

try {
  const { rows: tables } = await client.query(`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
    ORDER BY table_name
  `);

  const sections = [];
  for (const { table_name: tableName } of tables) {
    const { rows: cols } = await client.query(
      `
      SELECT column_name, data_type, udt_name, is_nullable
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = $1
      ORDER BY ordinal_position
      `,
      [tableName]
    );

    sections.push(renderTable(tableName, cols));
  }

  const swift = renderFile(sections);
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, swift);
  console.log(`wrote ${OUTPUT} (${tables.length} table(s))`);
} finally {
  await client.end();
}

// ---------------------------------------------------------------------------

function renderFile(sections) {
  return [
    "import Foundation",
    "",
    "// GENERATED FILE — do not edit. Run `npm run db:types` (or `make codegen`)",
    "// after schema changes. Generated by `scripts/gen-types.mjs`.",
    "//",
    "// Each table maps to an enum namespace containing a `Row: Codable` struct.",
    "// Use these as DTOs at the service boundary; map to/from your domain types",
    "// (e.g. Models/UserProfile.swift) inside the corresponding service.",
    "",
    "// swiftlint:disable nesting",
    "",
    sections.join("\n"),
    "// swiftlint:enable nesting",
    "",
  ].join("\n");
}

function renderTable(tableName, cols) {
  const namespace = pascalCase(tableName);
  const lines = [
    `enum ${namespace}Schema {`,
    `    /// Row shape for the \`public.${tableName}\` table.`,
    `    struct Row: Codable, Equatable {`,
  ];

  for (const c of cols) {
    const swiftName = camelCase(c.column_name);
    const swiftType = mapType(c);
    const optional = c.is_nullable === "YES" ? "?" : "";
    lines.push(`        let ${swiftName}: ${swiftType}${optional}`);
  }

  // CodingKeys when any column requires a snake_case → camelCase remap.
  const remapped = cols.filter(
    (c) => camelCase(c.column_name) !== c.column_name
  );
  if (remapped.length > 0) {
    lines.push("");
    lines.push("        enum CodingKeys: String, CodingKey {");
    for (const c of cols) {
      const swiftName = camelCase(c.column_name);
      if (swiftName === c.column_name) {
        lines.push(`            case ${swiftName}`);
      } else {
        lines.push(`            case ${swiftName} = "${c.column_name}"`);
      }
    }
    lines.push("        }");
  }

  lines.push("    }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// Postgres → Swift type mapping.
// `data_type` is the SQL standard name; `udt_name` is the Postgres-specific
// name (e.g. uuid, int4, jsonb). Prefer udt_name where the standard one is
// ambiguous ("USER-DEFINED" for enums, "ARRAY" for arrays).
function mapType({ data_type, udt_name }) {
  switch (udt_name) {
    case "uuid":
      return "UUID";
    case "text":
    case "varchar":
    case "bpchar":
    case "name":
    case "citext":
      return "String";
    case "int2":
    case "int4":
      return "Int";
    case "int8":
      return "Int64";
    case "float4":
      return "Float";
    case "float8":
    case "numeric":
      return "Double";
    case "bool":
      return "Bool";
    case "timestamptz":
    case "timestamp":
    case "date":
    case "time":
    case "timetz":
      return "Date";
    case "json":
    case "jsonb":
      return "Data";
    case "bytea":
      return "Data";
  }

  // Arrays land here as udt_name "_text", "_int4", etc.
  if (udt_name.startsWith("_")) {
    const inner = mapType({ data_type, udt_name: udt_name.slice(1) });
    return `[${inner}]`;
  }

  // Custom enums and anything else fall through to String. The DB still
  // validates on write; Swift just sees the raw value.
  console.warn(
    `warning: unmapped Postgres type ${udt_name} (data_type=${data_type}) — defaulting to String`
  );
  return "String";
}

function pascalCase(snake) {
  return snake
    .split("_")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function camelCase(snake) {
  const parts = snake.split("_");
  return (
    parts[0] + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("")
  );
}
